#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Memoize-ExpireLRU
Version  : 0.56
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Memoize-ExpireLRU-0.56.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Memoize-ExpireLRU-0.56.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmemoize-expirelru-perl/libmemoize-expirelru-perl_0.56-1.debian.tar.xz
Summary  : 'Expiry plug-in for Memoize that adds LRU cache expiration'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Memoize-ExpireLRU-license
Requires: perl-Memoize-ExpireLRU-man

%description
Memoize::ExpireLRU is a module that implements LRU expiration for
Memoize.
You can read a nicely formatted version of the documentation for
this module online:

%package license
Summary: license components for the perl-Memoize-ExpireLRU package.
Group: Default

%description license
license components for the perl-Memoize-ExpireLRU package.


%package man
Summary: man components for the perl-Memoize-ExpireLRU package.
Group: Default

%description man
man components for the perl-Memoize-ExpireLRU package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Memoize-ExpireLRU-0.56
mkdir -p %{_topdir}/BUILD/Memoize-ExpireLRU-0.56/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Memoize-ExpireLRU-0.56/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Memoize-ExpireLRU
cp LICENSE %{buildroot}/usr/share/doc/perl-Memoize-ExpireLRU/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Memoize/ExpireLRU.pm
/usr/lib/perl5/site_perl/5.26.1/auto/Memoize/ExpireLRU/DumpCache.al
/usr/lib/perl5/site_perl/5.26.1/auto/Memoize/ExpireLRU/ShowStats.al
/usr/lib/perl5/site_perl/5.26.1/auto/Memoize/ExpireLRU/autosplit.ix

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Memoize-ExpireLRU/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Memoize::ExpireLRU.3
