#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Memoize-ExpireLRU
Version  : 0.56
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Memoize-ExpireLRU-0.56.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Memoize-ExpireLRU-0.56.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmemoize-expirelru-perl/libmemoize-expirelru-perl_0.56-1.debian.tar.xz
Summary  : 'Expiry plug-in for Memoize that adds LRU cache expiration'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Memoize-ExpireLRU-license = %{version}-%{release}
Requires: perl-Memoize-ExpireLRU-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Memoize::ExpireLRU is a module that implements LRU expiration for
Memoize.
You can read a nicely formatted version of the documentation for
this module online:

%package dev
Summary: dev components for the perl-Memoize-ExpireLRU package.
Group: Development
Provides: perl-Memoize-ExpireLRU-devel = %{version}-%{release}
Requires: perl-Memoize-ExpireLRU = %{version}-%{release}

%description dev
dev components for the perl-Memoize-ExpireLRU package.


%package license
Summary: license components for the perl-Memoize-ExpireLRU package.
Group: Default

%description license
license components for the perl-Memoize-ExpireLRU package.


%package perl
Summary: perl components for the perl-Memoize-ExpireLRU package.
Group: Default
Requires: perl-Memoize-ExpireLRU = %{version}-%{release}

%description perl
perl components for the perl-Memoize-ExpireLRU package.


%prep
%setup -q -n Memoize-ExpireLRU-0.56
cd %{_builddir}
tar xf %{_sourcedir}/libmemoize-expirelru-perl_0.56-1.debian.tar.xz
cd %{_builddir}/Memoize-ExpireLRU-0.56
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Memoize-ExpireLRU-0.56/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Memoize-ExpireLRU
cp %{_builddir}/Memoize-ExpireLRU-0.56/LICENSE %{buildroot}/usr/share/package-licenses/perl-Memoize-ExpireLRU/61d16ea0946201fe0a4ab992cb42a5a578dd6dfc
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Memoize-ExpireLRU/4ded22b6400527cd73aa970102a10f1012a680a7
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Memoize::ExpireLRU.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Memoize-ExpireLRU/4ded22b6400527cd73aa970102a10f1012a680a7
/usr/share/package-licenses/perl-Memoize-ExpireLRU/61d16ea0946201fe0a4ab992cb42a5a578dd6dfc

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
